version: '3'

tasks:
  run-dev:
    desc: Run the project in development mode with docker-compose
    cmds:
      - sudo docker compose -f docker-compose.dev.yml up --build

  stop:
    desc: Stop all running containers
    cmds:
      - sudo docker compose -f docker-compose.dev.yml down

  logs:
    desc: Show logs from running containers
    cmds:
      - sudo docker compose -f docker-compose.dev.yml logs -f

  build:
    desc: Build the docker images
    cmds:
      - sudo docker compose -f docker-compose.dev.yml build

  db-init:
    desc: Initialize the local database and apply Django migrations
    cmds:
      - docker compose -f docker-compose.dev.yml up -d --wait db
      - docker compose -f docker-compose.dev.yml run --rm --no-deps backend python manage.py migrate

  migrate:
    desc: Run Django database migrations
    cmds:
      - sudo docker compose -f docker-compose.dev.yml exec -T backend python manage.py migrate

  load-test-data:
    desc: Initialize the local database and load predefined JSON test data
    aliases: [load-data]
    cmds:
      - task: db-init
      - docker compose -f docker-compose.dev.yml run --rm --no-deps backend python manage.py loaddata /code/Backend/backend/foodplaner/fixtures/test_data.json
