# Generated by Django 5.0.1 on 2024-08-13 18:48

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('title', models.CharField(max_length=180, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=1200, null=True)),
                ('preferedUnit', models.CharField(choices=[('kg', 'KG'), ('l', 'L'), ('g', 'G'), ('ml', 'ML'), ('stk', 'stk.'), ('tsp', 'TSP'), ('TBSP', 'Tbsp'), ('oz', 'Ounce'), ('cup', 'Cup'), ('gal', 'gallon'), ('pinch', 'prise'), ('drop', 'Tropfen'), ('handful', 'Handful'), ('sprig', 'Zweig'), ('Zehe', 'clove'), ('sheet', 'Blatt'), ('bottle', 'Flasche'), ('bund', 'bunch'), ('Package', 'package'), ('tafel', 'bar'), ('can', 'dose'), ('stick', 'stange')], default='stk', max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('description', models.TextField(max_length=500, null=True)),
                ('duration', models.PositiveSmallIntegerField(default=0)),
                ('preparation', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('unit', models.CharField(choices=[('kg', 'KG'), ('l', 'L'), ('g', 'G'), ('ml', 'ML'), ('stk', 'stk.'), ('tsp', 'TSP'), ('TBSP', 'Tbsp'), ('oz', 'Ounce'), ('cup', 'Cup'), ('gal', 'gallon'), ('pinch', 'prise'), ('drop', 'Tropfen'), ('handful', 'Handful'), ('sprig', 'Zweig'), ('Zehe', 'clove'), ('sheet', 'Blatt'), ('bottle', 'Flasche'), ('bund', 'bunch'), ('Package', 'package'), ('tafel', 'bar'), ('can', 'dose'), ('stick', 'stange')], default='stk', max_length=20)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodplaner.ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='FoodPlanerItem',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False, unique=True)),
                ('meals', models.ManyToManyField(blank=True, to='foodplaner.meal')),
            ],
        ),
        migrations.CreateModel(
            name='MealIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(max_length=10)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_to_meal', to='foodplaner.ingredient')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_to_ingredient', to='foodplaner.meal')),
            ],
            options={
                'db_table': 'meal_ingredient',
            },
        ),
        migrations.AddField(
            model_name='meal',
            name='ingredients',
            field=models.ManyToManyField(blank=True, through='foodplaner.MealIngredient', to='foodplaner.ingredient'),
        ),
        migrations.CreateModel(
            name='ShoppingListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bought', models.BooleanField(default=False)),
                ('added', models.DateTimeField(default=datetime.datetime(2024, 8, 13, 20, 48, 28, 42378))),
                ('amount', models.DecimalField(decimal_places=2, default=1, max_digits=10, null=True)),
                ('unit', models.CharField(choices=[('kg', 'KG'), ('l', 'L'), ('g', 'G'), ('ml', 'ML'), ('stk', 'stk.'), ('tsp', 'TSP'), ('TBSP', 'Tbsp'), ('oz', 'Ounce'), ('cup', 'Cup'), ('gal', 'gallon'), ('pinch', 'prise'), ('drop', 'Tropfen'), ('handful', 'Handful'), ('sprig', 'Zweig'), ('Zehe', 'clove'), ('sheet', 'Blatt'), ('bottle', 'Flasche'), ('bund', 'bunch'), ('Package', 'package'), ('tafel', 'bar'), ('can', 'dose'), ('stick', 'stange')], default='stk', max_length=20)),
                ('notes', models.TextField(blank=True, max_length=200, null=True)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodplaner.ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=datetime.datetime(2024, 8, 13, 20, 48, 28, 42378))),
                ('items', models.ManyToManyField(blank=True, to='foodplaner.shoppinglistitem')),
            ],
        ),
        migrations.CreateModel(
            name='IngredientTags',
            fields=[
                ('ingredient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='foodplaner.ingredient')),
                ('tags', models.ManyToManyField(blank=True, to='foodplaner.tag')),
            ],
        ),
        migrations.CreateModel(
            name='MealTags',
            fields=[
                ('meal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='foodplaner.meal')),
                ('tags', models.ManyToManyField(blank=True, to='foodplaner.tag')),
            ],
        ),
        migrations.AddConstraint(
            model_name='mealingredient',
            constraint=models.UniqueConstraint(fields=('meal', 'ingredient'), name='unique_meal_ingredient'),
        ),
    ]
