# Generated by Django 5.1 on 2024-08-28 09:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodplaner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='picture',
            field=models.ImageField(blank=True, help_text='Upload a picture of the meal', null=True, upload_to='meal_pictures/'),
        ),
        migrations.AddField(
            model_name='meal',
            name='portion_size',
            field=models.PositiveIntegerField(default=4, help_text='Portion size (number of servings)'),
        ),
        migrations.AlterField(
            model_name='shoppinglist',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 28, 11, 1, 39, 27223)),
        ),
        migrations.AlterField(
            model_name='shoppinglistitem',
            name='added',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 28, 11, 1, 39, 26220)),
        ),
    ]
