# Generated by Django 4.2.7 on 2023-11-19 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodplaner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('description', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='meal',
            name='description',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='meal',
            name='ingredients',
            field=models.ManyToManyField(to='foodplaner.ingredient'),
        ),
    ]
