# Generated by Django 4.2.7 on 2023-11-27 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodplaner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('title', models.CharField(max_length=180, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='meal',
            name='description',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='foodplaneritem',
            name='meals',
            field=models.ManyToManyField(blank=True, to='foodplaner.meal'),
        ),
        migrations.AddField(
            model_name='meal',
            name='ingredients',
            field=models.ManyToManyField(blank=True, to='foodplaner.ingredient'),
        ),
    ]
