# Generated by Django 4.2.3 on 2023-12-05 14:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodplaner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(default=datetime.datetime(2023, 12, 5, 15, 39, 54, 92974))),
                ('amount', models.DecimalField(decimal_places=2, default=1, max_digits=10, null=True)),
                ('unit', models.CharField(choices=[('kg', 'KG'), ('l', 'L'), ('g', 'G'), ('ml', 'ML'), ('stk', 'stk.'), ('tsp', 'TSP'), ('TBSP', 'Tbsp'), ('oz', 'Ounce'), ('cup', 'Cup'), ('gal', 'gallon'), ('pinch', 'prise'), ('drop', 'Tropfen'), ('handful', 'Handful'), ('sprig', 'Zweig'), ('Zehe', 'clove'), ('sheet', 'Blatt'), ('bottle', 'Flasche'), ('bund', 'bunch'), ('Package', 'package')], default='stk', max_length=20)),
                ('notes', models.TextField(blank=True, max_length=200, null=True)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodplaner.ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=datetime.datetime(2023, 12, 5, 15, 39, 54, 92974))),
                ('items', models.ManyToManyField(blank=True, to='foodplaner.shoppinglistitem')),
            ],
        ),
    ]
