# Generated by Django 5.1 on 2024-08-28 09:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodplaner', '0002_meal_picture_meal_portion_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppinglist',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 28, 11, 25, 17, 50660)),
        ),
        migrations.AlterField(
            model_name='shoppinglistitem',
            name='added',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 28, 11, 25, 17, 50660)),
        ),
    ]
