# Generated by Django 4.2.3 on 2023-12-05 14:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodplaner', '0003_alter_inventoryitem_unit_alter_shoppinglist_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinglistitem',
            name='bought',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='shoppinglist',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 5, 15, 59, 12, 271138)),
        ),
        migrations.AlterField(
            model_name='shoppinglistitem',
            name='added',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 5, 15, 59, 12, 270138)),
        ),
    ]
