# Generated by Django 4.2.3 on 2023-12-05 18:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodplaner', '0004_shoppinglistitem_bought_alter_shoppinglist_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='preferedUnit',
            field=models.CharField(default='stk', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='shoppinglist',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 5, 19, 59, 20, 301218)),
        ),
        migrations.AlterField(
            model_name='shoppinglistitem',
            name='added',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 5, 19, 59, 20, 301218)),
        ),
    ]
