# Generated by Django 5.0 on 2023-12-14 21:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodplaner', '0007_mealingredient_duration_mealingredient_preparation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mealingredient',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='mealingredient',
            name='preparation',
        ),
        migrations.AddField(
            model_name='meal',
            name='duration',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='meal',
            name='preparation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shoppinglist',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 14, 22, 22, 25, 261566)),
        ),
        migrations.AlterField(
            model_name='shoppinglistitem',
            name='added',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 14, 22, 22, 25, 261566)),
        ),
    ]
