# Generated by Django 5.0 on 2023-12-15 23:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodplaner', '0011_alter_mealingredient_ingredient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppinglist',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 16, 0, 17, 27, 431717)),
        ),
        migrations.AlterField(
            model_name='shoppinglistitem',
            name='added',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 16, 0, 17, 27, 430719)),
        ),
        migrations.AlterUniqueTogether(
            name='mealingredient',
            unique_together={('meal', 'ingredient')},
        ),
        migrations.AlterModelTable(
            name='mealingredient',
            table='meal_ingredient',
        ),
    ]
