# Generated by Django 5.0 on 2023-12-15 23:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodplaner', '0012_alter_shoppinglist_created_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mealingredient',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='shoppinglist',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 16, 0, 18, 53, 263450)),
        ),
        migrations.AlterField(
            model_name='shoppinglistitem',
            name='added',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 16, 0, 18, 53, 263450)),
        ),
        migrations.AddConstraint(
            model_name='mealingredient',
            constraint=models.UniqueConstraint(fields=('meal', 'ingredient'), name='unique_meal_ingredient'),
        ),
    ]
