# Generated by Django 5.0 on 2023-12-17 15:07

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodplaner', '0014_alter_ingredient_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='shoppinglist',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 17, 16, 7, 50, 295638)),
        ),
        migrations.AlterField(
            model_name='shoppinglistitem',
            name='added',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 17, 16, 7, 50, 294638)),
        ),
        migrations.CreateModel(
            name='MealTags',
            fields=[
                ('meal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='foodplaner.meal')),
                ('tags', models.ManyToManyField(blank=True, to='foodplaner.tag')),
            ],
        ),
        migrations.CreateModel(
            name='IngredientTags',
            fields=[
                ('ingredient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='foodplaner.ingredient')),
                ('tags', models.ManyToManyField(blank=True, to='foodplaner.tag')),
            ],
        ),
    ]
